# Generated by Django 5.1.2 on 2024-10-17 08:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 10, 17, 8, 13, 35, 565525, tzinfo=datetime.timezone.utc), verbose_name='Время (YYYY-MM-DD hh-mm)')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='Периодичность (дней)')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполение (секунд)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Признак публичности')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная приятная привычка')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('action',),
            },
        ),
    ]
